package com.example.Walkocity.accessingdatamysql;

import org.springframework.beans.factory.ObjectProvider;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.time.LocalDate;
import java.util.Optional;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private TrashcanRepository trashcanRepository;
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserAccountRepository userAccountRepository;
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="/add/coordinates") // Map ONLY POST Requests
    public @ResponseBody String addNewCoordinate (@RequestParam String longitude
            , @RequestParam String latitude, @RequestParam String liter) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Double longi = Double.parseDouble(longitude);
        Double lat = Double.parseDouble(latitude);
        Double lit = Double.parseDouble(liter);

        TrashCan c = new TrashCan();
        c.setLongitude(longi);
        c.setLatitude(lat);
        c.setLiter(lit);
        trashcanRepository.save(c);
        return "Saved";
    }

    @PostMapping(path="/add/useraccount") // Map ONLY POST Requests
    public @ResponseBody
    Optional<UserAccount> addNewUserAccount (@RequestParam String email, @RequestParam String password) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        UserAccount user = new UserAccount();
        user.setEmail(email);
        user.setPassword(password);
        user.setStartDate(LocalDate.now());
        userAccountRepository.save(user);
        return userAccountRepository.findById(user.getId());
    }

    @PostMapping(path="/add/user") // Map ONLY POST Requests
    public @ResponseBody
    Optional<User> addNewUserProfile (@RequestParam String id, @RequestParam String firstname, @RequestParam String lastname,
                                      @RequestParam String age, @RequestParam String gender, @RequestParam String country) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        User user = new User();
        user.setId(Integer.parseInt(id));
        user.setFirstName(firstname);
        user.setLastName(lastname);
        user.setAge(Integer.parseInt(age));
        user.setGender(gender);
        user.setCountry(country);
        //add language
        userRepository.save(user);
        return userRepository.findById(Integer.parseInt(id));
    }

    @GetMapping(path="/all/trashcans")
    public @ResponseBody Iterable<TrashCan> getAllCoordinates() {
        // This returns a JSON or XML with the users
        return trashcanRepository.findAll();
    }

    @GetMapping(path="/all/useraccounts")
    public @ResponseBody Iterable<UserAccount> getAllUserAccounts() {
        // This returns a JSON or XML with the users
        return userAccountRepository.findAll();
    }

    @GetMapping(path="/all/useraccount")
    public @ResponseBody UserAccount getUserAccount(@RequestParam String email) {
        UserAccount user = new UserAccount();
        user.setId(-1);
        for (UserAccount userAccount: userAccountRepository.findAll()) {
            if (userAccount.getEmail().equals(email)) {
                user.setId(userAccount.getId());
            }
        } return user;
    }

    @GetMapping(path="/all/login")
    public @ResponseBody UserAccount getUserAccount(@RequestParam String email, @RequestParam String password) {
        UserAccount user = new UserAccount();
        user.setId(-1);
        for (UserAccount userAccount: userAccountRepository.findAll()) {
            if (userAccount.getEmail().equals(email) && userAccount.getPassword().equals(password)) {
                user.setId(userAccount.getId());
            }
        } return user;
    }

    @GetMapping(path="/all/users")
    public @ResponseBody User getUser(@RequestParam Integer id) {
        User user = new User();
        user.setId(-1);
        for (User u: userRepository.findAll()) {
            if (u.getId().equals(id)) {
                user = u;
            }
        } return user;
    }

}